name: CI

on:
 push:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python-Version anzeigen
        run: python --version
